README.md
Found there is an extra step running the script after downloading as a zip file from github
=> Update macOS build instructions

build/build-macos, build/build-windows.ps1
Updating softdevice version used from 2.0.1 to 5.1.0 in win and mac build scripts
=> Update softdevice version in build scripts

build/bootloader-macos.sh, build/flash-macos.sh, build/flash-serial-macos.sh, build/flash-swd-macos.sh
Following some of the conventions laid out in the MacOS build script, these scripts match most of the scripts available for windows. I'm hoping to follow this up with a setup script that makes it easier for people to get started working with the repo and making key maps.
=> Initial build scripts for flashing on MacOS

build/build-windows.ps1
Creating patch to master to ensure build process succeeds.
=> Changing Name and SoftDevice Number for Windows Build

firmware/Key.cpp, firmware/Key.h, firmware/KeyScanner.cpp, firmware/KeyScanner.h, firmware/advanced_keycodes.h
Add support for transparent keys on non default layers
=> Feature trns

firmware/keyboards/crkbd/keymaps/default/keymap.cpp, firmware/keyboards/crkbd/keymaps/default/keymap.h, firmware/keyboards/crkbd/left/keyboard_config.h, firmware/keyboards/crkbd/master/keyboard_config.h, firmware/keyboards/crkbd/right/keyboard_config.h
Added crkbd (helidox) keyboard with default key mappings.
=> add crkbd keyboard

README.md
Requesting to add reference to nrf5240
=> comment on the nrf52840

firmware/firmware_main.cpp, firmware/keyboards/2x2test/keymaps/test/keymap.cpp, firmware/keyboards/2x2test/keymaps/test/keymap.h, firmware/keyboards/2x2test/master/keyboard_config.h
Added a 2x2 board for testing and the changes you suggested.
=> adding test board with 2 rows 2 columns, testing standard arduino read

firmware/keyboards/megatreus/keymaps/default/keymap.cpp, firmware/keyboards/megatreus/keymaps/default/keymap.h, firmware/keyboards/megatreus/master/keyboard_config.h
This is the keymap for my handwired build, do you accept this upstream as well?
=> Add the Megatreus keyboard

firmware/firmware_main.cpp, firmware/keymap.cpp
Also fix the build of the default keymap.cpp file.
=> Clean up the calling of sd_app_evt_wait

build/docker/nrf52840.sh
=> fixing board name for nrf52840 docker build script

build/windows/findserial.bat, build/windows/flash.bat, build/windows/flash840.bat, firmware/keyboards/4x4Tutorials/4x4Backpack/keyboard_config.h, firmware/keyboards/4x4Tutorials/4x4BackpacknRF52840/keyboard_config.h, firmware/keyboards/4x4Tutorials/4x4Platform/keyboard_config.h, firmware/keyboards/4x4Tutorials/keymaps/adjustlayer/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/adjustlayer/keymap.h, firmware/keyboards/4x4Tutorials/keymaps/base/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/base/keymap.h, firmware/keyboards/4x4Tutorials/keymaps/layers/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/layers/keymap.h, firmware/keyboards/4x4Tutorials/keymaps/spacecadet/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/spacecadet/keymap.h, firmware/keyboards/4x4Tutorials/keymaps/taphold/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/taphold/keymap.h, firmware/keyboards/4x4Tutorials/keymaps/tapholdlayer/keymap.cpp, firmware/keyboards/4x4Tutorials/keymaps/tapholdlayer/keymap.h
Created a new keyboard specifically to cover the tutorials in the video series.
This required the addition of a useful macro for simplifying the setup of the base layer and its use of the KEYMAP macro with the matrix initialization.
=> 4x4 tutorial

firmware/keyboards/lily58/left/keyboard_config.h, firmware/keyboards/lily58/master/keyboard_config.h, firmware/keyboards/lily58/right/keyboard_config.h
I've fixed a slight issue with the right side matrix of the lily58. Tested working on mine.
=> Fix lily58 right half matrix

build/windows/build.ps1
Added preferences and VID_PID that were apparently new to the build script.
=> updated windows build script to support BSP 0.20.5

docs/adding_keyboard.md, docs/building_firmware.md, docs/installing_tools.md
Made some smaller docs changes to clarify things in relation to nrf52840 and more.
=> Small tweaks to docs

build/macos/build-macos
Just a couple of small tweaks needed to get the macos build script to actually compile usable firmware on Mac OS
=> Update MacOS build script to work.

firmware/bluetooth.cpp, firmware/hid_keycodes.h
=> adding mouse speed selection keycodes

firmware/keyboards/crkbd/keymaps/bcat/keymap.cpp, firmware/keyboards/crkbd/keymaps/bcat/keymap.h, firmware/keyboards/crkbd/keymaps/bcat/readme.md
I wasn't 100% sure it was cool to add personal keymaps to the repo, but I saw some already, so I figured I'd send a pull request and see. :)
I didn't add copyright notices/license blocks to the source files, but can if you'd like me to do so.
=> Add Crkbd layout for bcat

firmware/KeyScanner.cpp, firmware/KeyScanner.h, firmware/keyboards/sofle/keymaps/default/keymap.cpp, firmware/keyboards/sofle/keymaps/default/keymap.h
=> updated sofle rotary encoder example to support layers

documentation/docs/flashing_firmware.md
Sorry if I'm meant to run docusaurus. I couldn't figure that out.
=> docs: update paths to linux build scripts

documentation/docusaurus.config.js
=> fix edit page links

documentation/docusaurus.config.js
=> update to edit links in documentation

firmware/datastructures.h, firmware/firmware_main.cpp
Simplified logic and made sure that only 1 task per loop runs.
=> Update to background task priorities and logic

firmware/KeyScanner.cpp, firmware/datastructures.h, firmware/firmware_main.cpp
=> added 125ms check for avoiding repeated keys

changelog.md, documentation/docs/configuring_firmware_3.md, firmware/datastructures.h, firmware/firmware_main.cpp, firmware/keyboards/4x4Backpack/keymaps/modes/keymap.cpp, firmware/keyboards/4x4Backpack/keymaps/modes/keymap.h
This will enable the keymap setup to be flexible and saved so that reboots won't impact the mode the board is in.
=> added user data to structs

firmware/keyboards/kyria/hardware/pca10056/nicenano/hardware_config.h, firmware/keyboards/kyria/keymaps/ddudek/keymap.cpp, firmware/keyboards/kyria/keymaps/ddudek/keymap.h
Working RGB backlight and 128x64 oled
=> Added config and keymap for Kyria working with nice nano v2

firmware/keyboards/bluehand/hardware/pca10056/bluehand/hardware_config.h, firmware/keyboards/bluehand/keymaps/sound_led/keymap.cpp, firmware/keyboards/bluehand/keymaps/sound_led/keymap.h
Example keymap for 2x4 bluehand demonstrating sound and led output
=> Bluehand sound_led keymap
